name: 'get current ui version'

on:
    workflow_dispatch:

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: get latest version from package.json
              id: latestversion
              run: |
                  echo "version=$(cat ./package.json | jq '.version' | sed 's/\"//g')" >> "$GITHUB_OUTPUT"
            - name: confirm version
              run: |
                  echo ${{ steps.latestversion.outputs.version }}
